FROM mcr.microsoft.com/dotnet/sdk:10.0
WORKDIR /app

RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

COPY *.csproj ./
RUN dotnet restore

COPY . ./

ENV ASPNETCORE_ENVIRONMENT=Development
ENV PORT=8080
EXPOSE 8080

ENTRYPOINT ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]
