[build]
builder = "nixpacks"

[deploy]
startCommand = "dotnet backend.dll"
healthcheckPath = "/swagger/index.html"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
