// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260618221734_AddUniqueEmailConstraints")]
    partial class AddUniqueEmailConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("PlacaVeiculo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placa_veiculo");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("backend.Models.Funcionario", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_funcionario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFuncionario"));

                    b.Property<int>("Cargo")
                        .HasColumnType("integer")
                        .HasColumnName("cargo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_funcionario");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<int>("TipoFuncionario")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_funcionario");

                    b.HasKey("IdFuncionario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("funcionarios");
                });

            modelBuilder.Entity("backend.Models.Revisao", b =>
                {
                    b.Property<int>("IdRevisao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_revisao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRevisao"));

                    b.Property<DateTime>("DatAgendamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_agendamento");

                    b.Property<DateTime>("DatFinalizacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dat_finalizacao");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdFuncionario")
                        .HasColumnType("integer")
                        .HasColumnName("id_funcionario");

                    b.Property<string>("StatusRevisao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status_revisao");

                    b.Property<int>("TipoRevisao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_revisao");

                    b.HasKey("IdRevisao");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdFuncionario");

                    b.ToTable("revisoes");
                });

            modelBuilder.Entity("backend.Models.Revisao", b =>
                {
                    b.HasOne("backend.Models.Cliente", "Cliente")
                        .WithMany("Revisoes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Funcionario", "Funcionario")
                        .WithMany("Revisoes")
                        .HasForeignKey("IdFuncionario");

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("backend.Models.Cliente", b =>
                {
                    b.Navigation("Revisoes");
                });

            modelBuilder.Entity("backend.Models.Funcionario", b =>
                {
                    b.Navigation("Revisoes");
                });
#pragma warning restore 612, 618
        }
    }
}
